### ISSUE TITLE
Install script fails when running from the VS Code PowerShell extension terminal

### ISSUE THREAD

**Issue by chadish7** [HP-85/atp#1]
When running the install script from the VSCode PowerShell extension terminal, the following error is produced:

Linux:
```
Invoke-WebRequest: 
Line |
  42 |      Invoke-WebRequest `
     |      ~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path '/home/ubuntu/.local/share/powershell/Modules /home/ubuntu/.vscode-server/extensions/ms-vscode.powershell-2024.2.2/modules/AWS.Tools.zip'.
```

Windows:
```
Invoke-WebRequest: 
Line |
  42 |      Invoke-WebRequest `
     |      ~~~~~~~~~~~~~~~~~~~
     | The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\user\Documents\PowerShell\Modules c:\Users\user\.vscode\extensions\ms-vscode.powershell-2024.2.2\modules\AWS.Tools.zip'
```

This has to do with [line 8-13](https://github.com/HP-85/atp/blob/main/AWS.Tools.Install.ps1#L8-L13) which returns 2 items when in the PowerShell extension terminal. Can be rectified by adding ` | Select-Object -First 1` to the end lines 8 and 13

**Comment by HP-85** [comment]
Added checks for homepath detection to select the 1st if multiple are returned, or to exit the script if none are detected.
